module.exports = {
    extends: [
        'plugin:vue/essential',
        '@vue/airbnb',
    ],
    env: {
        node: true,
    },
    parserOptions: {
        parser: 'babel-eslint',
    },
    rules: {
        'arrow-body-style': 'off',
        'arrow-parens': 0,
        'consistent-return': 'warn',
        'eqeqeq': 'off',
        'generator-star-spacing': 0,
        'import/extensions': ['error', 'ignorePackages'],
        'import/no-extraneous-dependencies': 'off',
        'import/no-unresolved': 'off',
        'indent': ['error', 4, { SwitchCase: 1 }],
        'max-len': ['warn', { code: 200, tabWidth: 4, ignoreStrings: true, ignoreTemplateLiterals: true }],
        'no-continue': 'off',
        'no-mixed-operators': 'off',
        'no-new': 'off',
        'no-param-reassign': 'off',
        'no-plusplus': 'off',
        'no-prototype-builtins': 'off',
        'no-restricted-syntax': 'off',
        'no-undef': 'off',
        'object-shorthand': ['error', 'always'],
        'prefer-const': ['warn', { destructuring: 'all' }],
        'prefer-destructuring': 'warn',
        'semi': ['error', 'always', { omitLastInOneLineBlock: true }],
    },
};
